//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventoFactory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compras
    {
        public int ID_Compra { get; set; }
        public int ID_Usuario { get; set; }
        public int ID_Ingresso { get; set; }
        public int QTD_Comprada { get; set; }
    
        public virtual Ingressos Ingressos { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
