//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("ServidorEventoModel", "FK_Compras_ID_Ingresso", "Ingressos", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(EventoFactory.Models.Ingressos), "Compras", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(EventoFactory.Models.Compras), true)]
[assembly: EdmRelationshipAttribute("ServidorEventoModel", "FK_Compras_ID_Usuario", "Usuarios", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(EventoFactory.Models.Usuarios), "Compras", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(EventoFactory.Models.Compras), true)]
[assembly: EdmRelationshipAttribute("ServidorEventoModel", "FK_Eventos_ID_Local", "Locais", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(EventoFactory.Models.Locais), "Eventos", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(EventoFactory.Models.Eventos), true)]
[assembly: EdmRelationshipAttribute("ServidorEventoModel", "FK_Feedbacks_ID_Evento", "Eventos", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(EventoFactory.Models.Eventos), "Feedbacks", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(EventoFactory.Models.Feedbacks), true)]
[assembly: EdmRelationshipAttribute("ServidorEventoModel", "FK_Ingressos_ID_Evento", "Eventos", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(EventoFactory.Models.Eventos), "Ingressos", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(EventoFactory.Models.Ingressos), true)]
[assembly: EdmRelationshipAttribute("ServidorEventoModel", "FK_Feedbacks_ID_Usuario", "Usuarios", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(EventoFactory.Models.Usuarios), "Feedbacks", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(EventoFactory.Models.Feedbacks), true)]

#endregion

namespace EventoFactory.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class ServidorEventoEntities1 : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new ServidorEventoEntities1 object using the connection string found in the 'ServidorEventoEntities1' section of the application configuration file.
        /// </summary>
        public ServidorEventoEntities1() : base("name=ServidorEventoEntities1", "ServidorEventoEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ServidorEventoEntities1 object.
        /// </summary>
        public ServidorEventoEntities1(string connectionString) : base(connectionString, "ServidorEventoEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ServidorEventoEntities1 object.
        /// </summary>
        public ServidorEventoEntities1(EntityConnection connection) : base(connection, "ServidorEventoEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Compras> Compras
        {
            get
            {
                if ((_Compras == null))
                {
                    _Compras = base.CreateObjectSet<Compras>("Compras");
                }
                return _Compras;
            }
        }
        private ObjectSet<Compras> _Compras;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Eventos> Eventos
        {
            get
            {
                if ((_Eventos == null))
                {
                    _Eventos = base.CreateObjectSet<Eventos>("Eventos");
                }
                return _Eventos;
            }
        }
        private ObjectSet<Eventos> _Eventos;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Feedbacks> Feedbacks
        {
            get
            {
                if ((_Feedbacks == null))
                {
                    _Feedbacks = base.CreateObjectSet<Feedbacks>("Feedbacks");
                }
                return _Feedbacks;
            }
        }
        private ObjectSet<Feedbacks> _Feedbacks;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Ingressos> Ingressos
        {
            get
            {
                if ((_Ingressos == null))
                {
                    _Ingressos = base.CreateObjectSet<Ingressos>("Ingressos");
                }
                return _Ingressos;
            }
        }
        private ObjectSet<Ingressos> _Ingressos;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Locais> Locais
        {
            get
            {
                if ((_Locais == null))
                {
                    _Locais = base.CreateObjectSet<Locais>("Locais");
                }
                return _Locais;
            }
        }
        private ObjectSet<Locais> _Locais;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Usuarios> Usuarios
        {
            get
            {
                if ((_Usuarios == null))
                {
                    _Usuarios = base.CreateObjectSet<Usuarios>("Usuarios");
                }
                return _Usuarios;
            }
        }
        private ObjectSet<Usuarios> _Usuarios;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Compras EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCompras(Compras compras)
        {
            base.AddObject("Compras", compras);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Eventos EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToEventos(Eventos eventos)
        {
            base.AddObject("Eventos", eventos);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Feedbacks EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToFeedbacks(Feedbacks feedbacks)
        {
            base.AddObject("Feedbacks", feedbacks);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Ingressos EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToIngressos(Ingressos ingressos)
        {
            base.AddObject("Ingressos", ingressos);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Locais EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToLocais(Locais locais)
        {
            base.AddObject("Locais", locais);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Usuarios EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUsuarios(Usuarios usuarios)
        {
            base.AddObject("Usuarios", usuarios);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ServidorEventoModel", Name="Compras")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Compras : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Compras object.
        /// </summary>
        /// <param name="iD_Compra">Initial value of the ID_Compra property.</param>
        /// <param name="iD_Usuario">Initial value of the ID_Usuario property.</param>
        /// <param name="iD_Ingresso">Initial value of the ID_Ingresso property.</param>
        public static Compras CreateCompras(global::System.Int32 iD_Compra, global::System.Int32 iD_Usuario, global::System.Int32 iD_Ingresso)
        {
            Compras compras = new Compras();
            compras.ID_Compra = iD_Compra;
            compras.ID_Usuario = iD_Usuario;
            compras.ID_Ingresso = iD_Ingresso;
            return compras;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID_Compra
        {
            get
            {
                return _ID_Compra;
            }
            set
            {
                if (_ID_Compra != value)
                {
                    OnID_CompraChanging(value);
                    ReportPropertyChanging("ID_Compra");
                    _ID_Compra = StructuralObject.SetValidValue(value, "ID_Compra");
                    ReportPropertyChanged("ID_Compra");
                    OnID_CompraChanged();
                }
            }
        }
        private global::System.Int32 _ID_Compra;
        partial void OnID_CompraChanging(global::System.Int32 value);
        partial void OnID_CompraChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID_Usuario
        {
            get
            {
                return _ID_Usuario;
            }
            set
            {
                OnID_UsuarioChanging(value);
                ReportPropertyChanging("ID_Usuario");
                _ID_Usuario = StructuralObject.SetValidValue(value, "ID_Usuario");
                ReportPropertyChanged("ID_Usuario");
                OnID_UsuarioChanged();
            }
        }
        private global::System.Int32 _ID_Usuario;
        partial void OnID_UsuarioChanging(global::System.Int32 value);
        partial void OnID_UsuarioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID_Ingresso
        {
            get
            {
                return _ID_Ingresso;
            }
            set
            {
                OnID_IngressoChanging(value);
                ReportPropertyChanging("ID_Ingresso");
                _ID_Ingresso = StructuralObject.SetValidValue(value, "ID_Ingresso");
                ReportPropertyChanged("ID_Ingresso");
                OnID_IngressoChanged();
            }
        }
        private global::System.Int32 _ID_Ingresso;
        partial void OnID_IngressoChanging(global::System.Int32 value);
        partial void OnID_IngressoChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ServidorEventoModel", "FK_Compras_ID_Ingresso", "Ingressos")]
        public Ingressos Ingressos
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Ingressos>("ServidorEventoModel.FK_Compras_ID_Ingresso", "Ingressos").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Ingressos>("ServidorEventoModel.FK_Compras_ID_Ingresso", "Ingressos").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Ingressos> IngressosReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Ingressos>("ServidorEventoModel.FK_Compras_ID_Ingresso", "Ingressos");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Ingressos>("ServidorEventoModel.FK_Compras_ID_Ingresso", "Ingressos", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ServidorEventoModel", "FK_Compras_ID_Usuario", "Usuarios")]
        public Usuarios Usuarios
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Usuarios>("ServidorEventoModel.FK_Compras_ID_Usuario", "Usuarios").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Usuarios>("ServidorEventoModel.FK_Compras_ID_Usuario", "Usuarios").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Usuarios> UsuariosReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Usuarios>("ServidorEventoModel.FK_Compras_ID_Usuario", "Usuarios");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Usuarios>("ServidorEventoModel.FK_Compras_ID_Usuario", "Usuarios", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ServidorEventoModel", Name="Eventos")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Eventos : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Eventos object.
        /// </summary>
        /// <param name="iD_Evento">Initial value of the ID_Evento property.</param>
        /// <param name="nome">Initial value of the Nome property.</param>
        /// <param name="iD_Local">Initial value of the ID_Local property.</param>
        public static Eventos CreateEventos(global::System.Int32 iD_Evento, global::System.String nome, global::System.Int32 iD_Local)
        {
            Eventos eventos = new Eventos();
            eventos.ID_Evento = iD_Evento;
            eventos.Nome = nome;
            eventos.ID_Local = iD_Local;
            return eventos;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID_Evento
        {
            get
            {
                return _ID_Evento;
            }
            set
            {
                if (_ID_Evento != value)
                {
                    OnID_EventoChanging(value);
                    ReportPropertyChanging("ID_Evento");
                    _ID_Evento = StructuralObject.SetValidValue(value, "ID_Evento");
                    ReportPropertyChanged("ID_Evento");
                    OnID_EventoChanged();
                }
            }
        }
        private global::System.Int32 _ID_Evento;
        partial void OnID_EventoChanging(global::System.Int32 value);
        partial void OnID_EventoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nome
        {
            get
            {
                return _Nome;
            }
            set
            {
                OnNomeChanging(value);
                ReportPropertyChanging("Nome");
                _Nome = StructuralObject.SetValidValue(value, false, "Nome");
                ReportPropertyChanged("Nome");
                OnNomeChanged();
            }
        }
        private global::System.String _Nome;
        partial void OnNomeChanging(global::System.String value);
        partial void OnNomeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Capacidade
        {
            get
            {
                return _Capacidade;
            }
            set
            {
                OnCapacidadeChanging(value);
                ReportPropertyChanging("Capacidade");
                _Capacidade = StructuralObject.SetValidValue(value, "Capacidade");
                ReportPropertyChanged("Capacidade");
                OnCapacidadeChanged();
            }
        }
        private Nullable<global::System.Int32> _Capacidade;
        partial void OnCapacidadeChanging(Nullable<global::System.Int32> value);
        partial void OnCapacidadeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Descricao
        {
            get
            {
                return _Descricao;
            }
            set
            {
                OnDescricaoChanging(value);
                ReportPropertyChanging("Descricao");
                _Descricao = StructuralObject.SetValidValue(value, true, "Descricao");
                ReportPropertyChanged("Descricao");
                OnDescricaoChanged();
            }
        }
        private global::System.String _Descricao;
        partial void OnDescricaoChanging(global::System.String value);
        partial void OnDescricaoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] Imagem
        {
            get
            {
                return StructuralObject.GetValidValue(_Imagem);
            }
            set
            {
                OnImagemChanging(value);
                ReportPropertyChanging("Imagem");
                _Imagem = StructuralObject.SetValidValue(value, true, "Imagem");
                ReportPropertyChanged("Imagem");
                OnImagemChanged();
            }
        }
        private global::System.Byte[] _Imagem;
        partial void OnImagemChanging(global::System.Byte[] value);
        partial void OnImagemChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID_Local
        {
            get
            {
                return _ID_Local;
            }
            set
            {
                OnID_LocalChanging(value);
                ReportPropertyChanging("ID_Local");
                _ID_Local = StructuralObject.SetValidValue(value, "ID_Local");
                ReportPropertyChanged("ID_Local");
                OnID_LocalChanged();
            }
        }
        private global::System.Int32 _ID_Local;
        partial void OnID_LocalChanging(global::System.Int32 value);
        partial void OnID_LocalChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ServidorEventoModel", "FK_Eventos_ID_Local", "Locais")]
        public Locais Locais
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Locais>("ServidorEventoModel.FK_Eventos_ID_Local", "Locais").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Locais>("ServidorEventoModel.FK_Eventos_ID_Local", "Locais").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Locais> LocaisReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Locais>("ServidorEventoModel.FK_Eventos_ID_Local", "Locais");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Locais>("ServidorEventoModel.FK_Eventos_ID_Local", "Locais", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ServidorEventoModel", "FK_Feedbacks_ID_Evento", "Feedbacks")]
        public EntityCollection<Feedbacks> Feedbacks
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Feedbacks>("ServidorEventoModel.FK_Feedbacks_ID_Evento", "Feedbacks");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Feedbacks>("ServidorEventoModel.FK_Feedbacks_ID_Evento", "Feedbacks", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ServidorEventoModel", "FK_Ingressos_ID_Evento", "Ingressos")]
        public EntityCollection<Ingressos> Ingressos
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Ingressos>("ServidorEventoModel.FK_Ingressos_ID_Evento", "Ingressos");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Ingressos>("ServidorEventoModel.FK_Ingressos_ID_Evento", "Ingressos", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ServidorEventoModel", Name="Feedbacks")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Feedbacks : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Feedbacks object.
        /// </summary>
        /// <param name="iD_Feedback">Initial value of the ID_Feedback property.</param>
        /// <param name="iD_Evento">Initial value of the ID_Evento property.</param>
        /// <param name="iD_Usuario">Initial value of the ID_Usuario property.</param>
        public static Feedbacks CreateFeedbacks(global::System.Int32 iD_Feedback, global::System.Int32 iD_Evento, global::System.Int32 iD_Usuario)
        {
            Feedbacks feedbacks = new Feedbacks();
            feedbacks.ID_Feedback = iD_Feedback;
            feedbacks.ID_Evento = iD_Evento;
            feedbacks.ID_Usuario = iD_Usuario;
            return feedbacks;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID_Feedback
        {
            get
            {
                return _ID_Feedback;
            }
            set
            {
                if (_ID_Feedback != value)
                {
                    OnID_FeedbackChanging(value);
                    ReportPropertyChanging("ID_Feedback");
                    _ID_Feedback = StructuralObject.SetValidValue(value, "ID_Feedback");
                    ReportPropertyChanged("ID_Feedback");
                    OnID_FeedbackChanged();
                }
            }
        }
        private global::System.Int32 _ID_Feedback;
        partial void OnID_FeedbackChanging(global::System.Int32 value);
        partial void OnID_FeedbackChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Nota
        {
            get
            {
                return _Nota;
            }
            set
            {
                OnNotaChanging(value);
                ReportPropertyChanging("Nota");
                _Nota = StructuralObject.SetValidValue(value, "Nota");
                ReportPropertyChanged("Nota");
                OnNotaChanged();
            }
        }
        private Nullable<global::System.Decimal> _Nota;
        partial void OnNotaChanging(Nullable<global::System.Decimal> value);
        partial void OnNotaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Comentario
        {
            get
            {
                return _Comentario;
            }
            set
            {
                OnComentarioChanging(value);
                ReportPropertyChanging("Comentario");
                _Comentario = StructuralObject.SetValidValue(value, true, "Comentario");
                ReportPropertyChanged("Comentario");
                OnComentarioChanged();
            }
        }
        private global::System.String _Comentario;
        partial void OnComentarioChanging(global::System.String value);
        partial void OnComentarioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID_Evento
        {
            get
            {
                return _ID_Evento;
            }
            set
            {
                OnID_EventoChanging(value);
                ReportPropertyChanging("ID_Evento");
                _ID_Evento = StructuralObject.SetValidValue(value, "ID_Evento");
                ReportPropertyChanged("ID_Evento");
                OnID_EventoChanged();
            }
        }
        private global::System.Int32 _ID_Evento;
        partial void OnID_EventoChanging(global::System.Int32 value);
        partial void OnID_EventoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID_Usuario
        {
            get
            {
                return _ID_Usuario;
            }
            set
            {
                OnID_UsuarioChanging(value);
                ReportPropertyChanging("ID_Usuario");
                _ID_Usuario = StructuralObject.SetValidValue(value, "ID_Usuario");
                ReportPropertyChanged("ID_Usuario");
                OnID_UsuarioChanged();
            }
        }
        private global::System.Int32 _ID_Usuario;
        partial void OnID_UsuarioChanging(global::System.Int32 value);
        partial void OnID_UsuarioChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ServidorEventoModel", "FK_Feedbacks_ID_Evento", "Eventos")]
        public Eventos Eventos
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Eventos>("ServidorEventoModel.FK_Feedbacks_ID_Evento", "Eventos").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Eventos>("ServidorEventoModel.FK_Feedbacks_ID_Evento", "Eventos").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Eventos> EventosReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Eventos>("ServidorEventoModel.FK_Feedbacks_ID_Evento", "Eventos");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Eventos>("ServidorEventoModel.FK_Feedbacks_ID_Evento", "Eventos", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ServidorEventoModel", "FK_Feedbacks_ID_Usuario", "Usuarios")]
        public Usuarios Usuarios
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Usuarios>("ServidorEventoModel.FK_Feedbacks_ID_Usuario", "Usuarios").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Usuarios>("ServidorEventoModel.FK_Feedbacks_ID_Usuario", "Usuarios").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Usuarios> UsuariosReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Usuarios>("ServidorEventoModel.FK_Feedbacks_ID_Usuario", "Usuarios");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Usuarios>("ServidorEventoModel.FK_Feedbacks_ID_Usuario", "Usuarios", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ServidorEventoModel", Name="Ingressos")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Ingressos : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Ingressos object.
        /// </summary>
        /// <param name="iD_Ingresso">Initial value of the ID_Ingresso property.</param>
        /// <param name="preco">Initial value of the Preco property.</param>
        /// <param name="quantidade_Inicial">Initial value of the Quantidade_Inicial property.</param>
        /// <param name="iD_Evento">Initial value of the ID_Evento property.</param>
        public static Ingressos CreateIngressos(global::System.Int32 iD_Ingresso, global::System.Decimal preco, global::System.Int32 quantidade_Inicial, global::System.Int32 iD_Evento)
        {
            Ingressos ingressos = new Ingressos();
            ingressos.ID_Ingresso = iD_Ingresso;
            ingressos.Preco = preco;
            ingressos.Quantidade_Inicial = quantidade_Inicial;
            ingressos.ID_Evento = iD_Evento;
            return ingressos;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID_Ingresso
        {
            get
            {
                return _ID_Ingresso;
            }
            set
            {
                if (_ID_Ingresso != value)
                {
                    OnID_IngressoChanging(value);
                    ReportPropertyChanging("ID_Ingresso");
                    _ID_Ingresso = StructuralObject.SetValidValue(value, "ID_Ingresso");
                    ReportPropertyChanged("ID_Ingresso");
                    OnID_IngressoChanged();
                }
            }
        }
        private global::System.Int32 _ID_Ingresso;
        partial void OnID_IngressoChanging(global::System.Int32 value);
        partial void OnID_IngressoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Preco
        {
            get
            {
                return _Preco;
            }
            set
            {
                OnPrecoChanging(value);
                ReportPropertyChanging("Preco");
                _Preco = StructuralObject.SetValidValue(value, "Preco");
                ReportPropertyChanged("Preco");
                OnPrecoChanged();
            }
        }
        private global::System.Decimal _Preco;
        partial void OnPrecoChanging(global::System.Decimal value);
        partial void OnPrecoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Quantidade_Inicial
        {
            get
            {
                return _Quantidade_Inicial;
            }
            set
            {
                OnQuantidade_InicialChanging(value);
                ReportPropertyChanging("Quantidade_Inicial");
                _Quantidade_Inicial = StructuralObject.SetValidValue(value, "Quantidade_Inicial");
                ReportPropertyChanged("Quantidade_Inicial");
                OnQuantidade_InicialChanged();
            }
        }
        private global::System.Int32 _Quantidade_Inicial;
        partial void OnQuantidade_InicialChanging(global::System.Int32 value);
        partial void OnQuantidade_InicialChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> QTD_Vendida
        {
            get
            {
                return _QTD_Vendida;
            }
            set
            {
                OnQTD_VendidaChanging(value);
                ReportPropertyChanging("QTD_Vendida");
                _QTD_Vendida = StructuralObject.SetValidValue(value, "QTD_Vendida");
                ReportPropertyChanged("QTD_Vendida");
                OnQTD_VendidaChanged();
            }
        }
        private Nullable<global::System.Int32> _QTD_Vendida;
        partial void OnQTD_VendidaChanging(Nullable<global::System.Int32> value);
        partial void OnQTD_VendidaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID_Evento
        {
            get
            {
                return _ID_Evento;
            }
            set
            {
                OnID_EventoChanging(value);
                ReportPropertyChanging("ID_Evento");
                _ID_Evento = StructuralObject.SetValidValue(value, "ID_Evento");
                ReportPropertyChanged("ID_Evento");
                OnID_EventoChanged();
            }
        }
        private global::System.Int32 _ID_Evento;
        partial void OnID_EventoChanging(global::System.Int32 value);
        partial void OnID_EventoChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ServidorEventoModel", "FK_Compras_ID_Ingresso", "Compras")]
        public EntityCollection<Compras> Compras
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Compras>("ServidorEventoModel.FK_Compras_ID_Ingresso", "Compras");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Compras>("ServidorEventoModel.FK_Compras_ID_Ingresso", "Compras", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ServidorEventoModel", "FK_Ingressos_ID_Evento", "Eventos")]
        public Eventos Eventos
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Eventos>("ServidorEventoModel.FK_Ingressos_ID_Evento", "Eventos").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Eventos>("ServidorEventoModel.FK_Ingressos_ID_Evento", "Eventos").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Eventos> EventosReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Eventos>("ServidorEventoModel.FK_Ingressos_ID_Evento", "Eventos");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Eventos>("ServidorEventoModel.FK_Ingressos_ID_Evento", "Eventos", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ServidorEventoModel", Name="Locais")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Locais : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Locais object.
        /// </summary>
        /// <param name="iD_Local">Initial value of the ID_Local property.</param>
        /// <param name="endereco">Initial value of the Endereco property.</param>
        public static Locais CreateLocais(global::System.Int32 iD_Local, global::System.String endereco)
        {
            Locais locais = new Locais();
            locais.ID_Local = iD_Local;
            locais.Endereco = endereco;
            return locais;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID_Local
        {
            get
            {
                return _ID_Local;
            }
            set
            {
                if (_ID_Local != value)
                {
                    OnID_LocalChanging(value);
                    ReportPropertyChanging("ID_Local");
                    _ID_Local = StructuralObject.SetValidValue(value, "ID_Local");
                    ReportPropertyChanged("ID_Local");
                    OnID_LocalChanged();
                }
            }
        }
        private global::System.Int32 _ID_Local;
        partial void OnID_LocalChanging(global::System.Int32 value);
        partial void OnID_LocalChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Endereco
        {
            get
            {
                return _Endereco;
            }
            set
            {
                OnEnderecoChanging(value);
                ReportPropertyChanging("Endereco");
                _Endereco = StructuralObject.SetValidValue(value, false, "Endereco");
                ReportPropertyChanged("Endereco");
                OnEnderecoChanged();
            }
        }
        private global::System.String _Endereco;
        partial void OnEnderecoChanging(global::System.String value);
        partial void OnEnderecoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Numero
        {
            get
            {
                return _Numero;
            }
            set
            {
                OnNumeroChanging(value);
                ReportPropertyChanging("Numero");
                _Numero = StructuralObject.SetValidValue(value, "Numero");
                ReportPropertyChanged("Numero");
                OnNumeroChanged();
            }
        }
        private Nullable<global::System.Int32> _Numero;
        partial void OnNumeroChanging(Nullable<global::System.Int32> value);
        partial void OnNumeroChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Bairro
        {
            get
            {
                return _Bairro;
            }
            set
            {
                OnBairroChanging(value);
                ReportPropertyChanging("Bairro");
                _Bairro = StructuralObject.SetValidValue(value, true, "Bairro");
                ReportPropertyChanged("Bairro");
                OnBairroChanged();
            }
        }
        private global::System.String _Bairro;
        partial void OnBairroChanging(global::System.String value);
        partial void OnBairroChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CEP
        {
            get
            {
                return _CEP;
            }
            set
            {
                OnCEPChanging(value);
                ReportPropertyChanging("CEP");
                _CEP = StructuralObject.SetValidValue(value, true, "CEP");
                ReportPropertyChanged("CEP");
                OnCEPChanged();
            }
        }
        private global::System.String _CEP;
        partial void OnCEPChanging(global::System.String value);
        partial void OnCEPChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Descricao
        {
            get
            {
                return _Descricao;
            }
            set
            {
                OnDescricaoChanging(value);
                ReportPropertyChanging("Descricao");
                _Descricao = StructuralObject.SetValidValue(value, true, "Descricao");
                ReportPropertyChanged("Descricao");
                OnDescricaoChanged();
            }
        }
        private global::System.String _Descricao;
        partial void OnDescricaoChanging(global::System.String value);
        partial void OnDescricaoChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ServidorEventoModel", "FK_Eventos_ID_Local", "Eventos")]
        public EntityCollection<Eventos> Eventos
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Eventos>("ServidorEventoModel.FK_Eventos_ID_Local", "Eventos");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Eventos>("ServidorEventoModel.FK_Eventos_ID_Local", "Eventos", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ServidorEventoModel", Name="Usuarios")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Usuarios : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Usuarios object.
        /// </summary>
        /// <param name="iD_Usuario">Initial value of the ID_Usuario property.</param>
        /// <param name="nome">Initial value of the Nome property.</param>
        /// <param name="usuario">Initial value of the Usuario property.</param>
        /// <param name="senha">Initial value of the Senha property.</param>
        /// <param name="perfil">Initial value of the Perfil property.</param>
        public static Usuarios CreateUsuarios(global::System.Int32 iD_Usuario, global::System.String nome, global::System.String usuario, global::System.String senha, global::System.String perfil)
        {
            Usuarios usuarios = new Usuarios();
            usuarios.ID_Usuario = iD_Usuario;
            usuarios.Nome = nome;
            usuarios.Usuario = usuario;
            usuarios.Senha = senha;
            usuarios.Perfil = perfil;
            return usuarios;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID_Usuario
        {
            get
            {
                return _ID_Usuario;
            }
            set
            {
                if (_ID_Usuario != value)
                {
                    OnID_UsuarioChanging(value);
                    ReportPropertyChanging("ID_Usuario");
                    _ID_Usuario = StructuralObject.SetValidValue(value, "ID_Usuario");
                    ReportPropertyChanged("ID_Usuario");
                    OnID_UsuarioChanged();
                }
            }
        }
        private global::System.Int32 _ID_Usuario;
        partial void OnID_UsuarioChanging(global::System.Int32 value);
        partial void OnID_UsuarioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nome
        {
            get
            {
                return _Nome;
            }
            set
            {
                OnNomeChanging(value);
                ReportPropertyChanging("Nome");
                _Nome = StructuralObject.SetValidValue(value, false, "Nome");
                ReportPropertyChanged("Nome");
                OnNomeChanged();
            }
        }
        private global::System.String _Nome;
        partial void OnNomeChanging(global::System.String value);
        partial void OnNomeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Usuario
        {
            get
            {
                return _Usuario;
            }
            set
            {
                OnUsuarioChanging(value);
                ReportPropertyChanging("Usuario");
                _Usuario = StructuralObject.SetValidValue(value, false, "Usuario");
                ReportPropertyChanged("Usuario");
                OnUsuarioChanged();
            }
        }
        private global::System.String _Usuario;
        partial void OnUsuarioChanging(global::System.String value);
        partial void OnUsuarioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Senha
        {
            get
            {
                return _Senha;
            }
            set
            {
                OnSenhaChanging(value);
                ReportPropertyChanging("Senha");
                _Senha = StructuralObject.SetValidValue(value, false, "Senha");
                ReportPropertyChanged("Senha");
                OnSenhaChanged();
            }
        }
        private global::System.String _Senha;
        partial void OnSenhaChanging(global::System.String value);
        partial void OnSenhaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, true, "Email");
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Perfil
        {
            get
            {
                return _Perfil;
            }
            set
            {
                OnPerfilChanging(value);
                ReportPropertyChanging("Perfil");
                _Perfil = StructuralObject.SetValidValue(value, false, "Perfil");
                ReportPropertyChanged("Perfil");
                OnPerfilChanged();
            }
        }
        private global::System.String _Perfil;
        partial void OnPerfilChanging(global::System.String value);
        partial void OnPerfilChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ServidorEventoModel", "FK_Compras_ID_Usuario", "Compras")]
        public EntityCollection<Compras> Compras
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Compras>("ServidorEventoModel.FK_Compras_ID_Usuario", "Compras");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Compras>("ServidorEventoModel.FK_Compras_ID_Usuario", "Compras", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ServidorEventoModel", "FK_Feedbacks_ID_Usuario", "Feedbacks")]
        public EntityCollection<Feedbacks> Feedbacks
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Feedbacks>("ServidorEventoModel.FK_Feedbacks_ID_Usuario", "Feedbacks");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Feedbacks>("ServidorEventoModel.FK_Feedbacks_ID_Usuario", "Feedbacks", value);
                }
            }
        }

        #endregion

    }

    #endregion

}
