//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventoFactory.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ServidorEventoEntities : DbContext
    {
        public ServidorEventoEntities()
            : base("name=ServidorEventoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Compras> Compras { get; set; }
        public DbSet<Eventos> Eventos { get; set; }
        public DbSet<Feedbacks> Feedbacks { get; set; }
        public DbSet<Ingressos> Ingressos { get; set; }
        public DbSet<Locais> Locais { get; set; }
        public DbSet<Usuarios> Usuarios { get; set; }
    }
}
