//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventoFactory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ingressos
    {
        public Ingressos()
        {
            this.Compras = new HashSet<Compras>();
            this.Eventos = new HashSet<Eventos>();
        }
    
        public int ID_Ingresso { get; set; }
        public decimal Preco { get; set; }
        public int Quantidade_Inicial { get; set; }
        public Nullable<int> QTD_Vendida { get; set; }
    
        public virtual ICollection<Compras> Compras { get; set; }
        public virtual ICollection<Eventos> Eventos { get; set; }
    }
}
